import os
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

# Set a clean, modern aesthetic for our charts
sns.set_theme(style="whitegrid")
plt.rcParams.update({"font.size": 10, "axes.labelsize": 12, "axes.titlesize": 14})


def run_post_preprocessing_eda(processed_file_path):
    """Loads the preprocessed training dataset and generates an advanced

    3-panel model insight dashboard.
    """
    if not os.path.exists(processed_file_path):
        raise FileNotFoundError(
            f"Could not find preprocessed training sheet at: {processed_file_path}\n"
            f"Please run your 'data_preprocessing.py' pipeline file first!"
        )

    print("📊 Loading preprocessed training dataset for EDA...")
    df = pd.read_csv(processed_file_path)
    print(f"   Loaded Matrix Shape: {df.shape}")

    # --- SETUP MULTI-PANEL DASHBOARD CANVAS ---
    fig, axes = plt.subplots(1, 3, figsize=(20, 6))
    fig.suptitle(
        "ZAMEEN REAL ESTATE ENGINE - POST-PREPROCESSING DIAGNOSTIC DASHBOARD",
        fontsize=16,
        weight="bold",
        y=1.02,
    )

    # =========================================================================
    # CHART 4: POST-TRANSFORMATION TARGET DISTRIBUTION (BELL CURVE VALIDATION)
    # =========================================================================
    print("📈 Generating Chart 4: Target Log Price Distribution...")
    sns.histplot(
        data=df,
        x="target_log_price",
        kde=True,
        color="#2b5c8f",
        bins=40,
        ax=axes[0],
    )
    axes[0].set_title("Target Variance Symmetrization Check")
    axes[0].set_xlabel("Log Transformed Price [np.log1p(PKR)]")
    axes[0].set_ylabel("Property Row Frequency Count")

    # =========================================================================
    # CHART 5: THE REAL ESTATE ENGINE (AREA SQFT VS LOG PRICE SCATTER)
    # =========================================================================
    print("🗺️ Generating Chart 5: Standardized Size vs. Price Scatter...")
    # Taking a random sampling slice of 5,000 rows if the dataset is massive
    # to prevent canvas over-plotting and keep rendering speed fast.
    sample_df = df.sample(n=min(5000, len(df)), random_state=42)

    sns.regplot(
        data=sample_df,
        x="area_sqft",
        y="target_log_price",
        scatter_kws={"alpha": 0.4, "color": "#4a90e2", "edgecolor": "w", "s": 25},
        line_kws={"color": "#d0021b", "linewidth": 2.5},
        ax=axes[1],
    )
    axes[1].set_title("Standardized Footprint Elasticity")
    axes[1].set_xlabel("Scaled Structural Area (Standardized Sq Ft)")
    axes[1].set_ylabel("Log Transformed Price")

    # =========================================================================
    # CHART 6: FEATURE INTERACTION GRID (CORRELATION MATRIX HEATMAP)
    # =========================================================================
    print("🧮 Generating Chart 6: Feature Interaction Correlation Heatmap...")
    # Isolate continuous variables and the target column
    continuous_cols = [
        "bedrooms",
        "bathrooms",
        "area_sqft",
        "location_encoded",
        "target_log_price",
    ]

    # Dynamically match coordinate columns if they exist in your exported sheet
    spatial_cols = [c for c in ["latitude", "longitude"] if c in df.columns]
    target_matrix_cols = continuous_cols + spatial_cols

    # Calculate Pearson linear correlation coefficients matrix
    corr_matrix = df[target_matrix_cols].corr()

    sns.heatmap(
        corr_matrix,
        annot=True,
        cmap="RdBu_r",
        fmt=".2f",
        vmin=-1,
        vmax=1,
        center=0,
        square=True,
        cbar_kws={"shrink": 0.75},
        ax=axes[2],
    )
    axes[2].set_title("Multicollinearity & Predictive Weight Grid")
    plt.setp(axes[2].get_xticklabels(), rotation=45, ha="right")

    # Adjust layout padding so borders don't overlap labels
    plt.tight_layout()

    # Save a static high-resolution image copy straight into your reports/plots directory
    output_dir = os.path.dirname(processed_file_path)
    save_path = os.path.join(output_dir, "post_processed_eda_dashboard.png")
    plt.savefig(save_path, bbox_inches="tight", dpi=300)
    print(f"💾 High-resolution dashboard image saved to: {save_path}")

    # Render window display onto monitor
    print("🖥️ Opening interactive visualization display windows...")
    plt.show()


if __name__ == "__main__":
    # Point directly to your clean processed file output path generated by step 9
    PROCESSED_TRAIN_FILE = r"D:\Data Science Projects\Property-Price-Detection\Data\Processed\zameen_train_preprocessed.csv"

    run_post_preprocessing_eda(PROCESSED_TRAIN_FILE)
