services:
  # --- BACKEND SERVICE CHANNEL ---
  valuation_api:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: zameen_api_image:latest
    container_name: zameen_api_service
    ports:
      - "8000:8000"
    restart: always

  # --- FRONTEND SERVICE CHANNEL ---
  valuation_app:
    build:
      context: .
      dockerfile: Dockerfile.app
    image: zameen_app_image:latest
    container_name: zameen_streamlit_service
    ports:
      - "8501:8501"
    depends_on:
      - valuation_api
    restart: always